// Análisis por deltas de tiempo generados de un reporte anterior
// TODO: Hasta ahora no se usa ese `int n`, pero en las funciones
//       está indicando algo así como el número de estados
void RegistrarDeltas(int n){
	Cabecera("Analysis using delta times");

	InfoGrlRegistro();
	RegNombre.insert(0, RutaRegistro);

	long long int entrada1 = 0, entrada2;
	int iterador = 0;
	for (int j=0; j<100000; j++){
		registro[0][j] = 0;
		registro[1][j] = 0;
	}
	
	cout << "    Enter the delta times previously generated by this program." << endl
		 << "    Make sure to enter -1 at the end of the data." << endl
		 << "    Skip any value that is not a number." << endl
		 << endl
		 << "    Ready to receive the data:" << endl
		 << "    ";

	while (entrada1 != -1){
		cin >> entrada1;
		if (entrada1 != -1){
			cin >> entrada2;
			registro[0][iterador] = entrada1;
			registro[1][iterador] = entrada2;
			iterador++;
			cout << "    ";
		}
	}
	TiemposCont = iterador;
	cout << endl;
	return;
}